---
title: "Analyses"
author: "Vera Weisbecker and Cruise Speck"
date: "5 December 2018"
output: html_document
---



## load required packages and processed data



```{r }
library(ape)
library(geiger)
library(caper)
library(car)
library(multcomp)
library(geomorph)
library(lmSupport)
library(ggplot2)
library(nlme)

#the "utilities" file contains functions so this analysis page isn't too cluttered
source("../Analyses/Utilities.r")
load(file = "../Data/Processed_Data_for_Pgls.rda")



```

#is there a difference in tail/body length relationships between the sexes or if we use maximum tail length?

```{r}
#Marsupials:

  ##Re-arrange datasets to put males, femals and averages under each other, turning into a data frame for column names
  
  Males<-cbind(marsFull$Tl_Av_M,marsFull$Bl_Av_M,marsFull$Wt_Av_M, marsFull$Locomotor_use,rep(1,length(marsFull$Tl_Av_M)))
  Females<-cbind(marsFull$Tl_Av_F,marsFull$Bl_Av_F,marsFull$Wt_Av_F,marsFull$Locomotor_use, rep(2,length(marsFull$Tl_Av_F)))
  Averages<-cbind(marsFull$Tl_mm, marsFull$Bl_mm,marsFull$Wt_g, marsFull$Locomotor_use,rep(3,length(marsFull$Bl_mm)))
  
  Combine=rbind(Males, Females,Averages)
  Combine=as.data.frame(Combine)
  colnames(Combine) <-c("Tl","Bl","Wt","Locomotor_use","Sex")
  Combine$Sex<-as.factor(Combine$Sex)
  Combine$Locomotor_use<-as.factor(Combine$Locomotor_use)
  
  ##Are there differences in slope of Tail length and body LENGTH according to locomotor use, sex, or averages between sexes?
  Sex_locomotion=summary(lm(Combine$Tl~Combine$Bl*Combine$Sex*Combine$Locomotor_use))
  Sex_locomotion=aov (Combine$Tl~Combine$Bl*Combine$Sex*Combine$Locomotor_use)
  
  ##If significant interactions, use
  testInteractions(Sex_locomotion)
  #if not, re-run without interactions; if any intercept is significant, run something like the below
  TukeyHSD(MaleFemaleaov,which='Sex', data=Combine )
  
  ##Are there differences in slope of Tail length and body WEIGHT according to locomotor use, sex, or averages between sexes?
  Sex_locomotion=summary(lm(Combine$Tl~Combine$Wt *Combine$Sex*Combine$Locomotor_use))
  Sex_locomotion=aov (Combine$Tl~Combine$Wt*Combine$Sex*Combine$Locomotor_use)
  
  ##If significant interactions, use
  testInteractions(Sex_locomotion)
  #if not, re-run without interactions; if any intercept is significant, run something like the below
  TukeyHSD(MaleFemaleaov,which='Sex', data=Combine )

#Rodents:

  Males<-cbind(rodFull$Tl_Av_M,rodFull$Bl_Av_M,rodFull$Wt_Av_M, rodFull$Locomotor_use,rep(1,length(rodFull$Tl_Av_M)))
  Females<-cbind(rodFull$Tl_Av_F,rodFull$Bl_Av_F,rodFull$Wt_Av_F,rodFull$Locomotor_use, rep(2,length(rodFull$Tl_Av_F)))
  Averages<-cbind(rodFull$Tl_mm, rodFull$Bl_mm,rodFull$Wt_g, rodFull$Locomotor_use,rep(3,length(rodFull$Bl_mm)))
  
  Combine=rbind(Males, Females,Averages)
  Combine=as.data.frame(Combine)
  colnames(Combine) <-c("Tl","Bl","Wt","Locomotor_use","Sex")
  Combine$Sex<-as.factor(Combine$Sex)
  Combine$Locomotor_use<-as.factor(Combine$Locomotor_use)
  
  #Are there differences in slope of Tail length and body LENGTH according to locomotor use, sex, or averages between sexes?
  Sex_locomotion=summary(lm(Combine$Tl~Combine$Bl*Combine$Sex*Combine$Locomotor_use))
  Sex_locomotion=aov (Combine$Tl~Combine$Bl*Combine$Sex*Combine$Locomotor_use)
  
  #If significant interactions, use
  testInteractions(Sex_locomotion)
  #if not, re-run without interactions; if any intercept is significant, run something like the below
  TukeyHSD(MaleFemaleaov,which='Sex', data=Combine )
  
  #Are there differences in slope of Tail length and body WEIGHT according to locomotor use, sex, or averages between sexes?
  Sex_locomotion=summary(lm(Combine$Tl~Combine$Wt *Combine$Sex*Combine$Locomotor_use))
  Sex_locomotion=aov (Combine$Tl~Combine$Wt*Combine$Sex*Combine$Locomotor_use)
  
  #If significant interactions, use
  testInteractions(Sex_locomotion)
  #if not, re-run without interactions; if any intercept is significant, run something like the below
  TukeyHSD(MaleFemaleaov,which='Sex', data=Combine )


```


#the below is messy experimentation and needs cleaning up
```{r}


# do males and females display similar body/tail length scaling patterns? 

  ##find best model
  TB_males=find.best.model(Tl_M~Bl_M,marsTree_sexes,mars_sexes);TB_males$AIC_Weights
  TB_females=find.best.model(Tl_F~Bl_F,marsTree_sexes,mars_sexes);TB_females$AIC_Weights

  ##compare statistics; these are near-identical
  TB_males$Model_summaries$corBrownian$tTable
  TB_females$Model_summaries$corBrownian$tTable

  ##now compare to joint averaged dataset
  Tlength_Blength=find.best.model(Tlength_mm~Blength_mm,marsTree,mars)
  Tlength_Blength$AIC_Weights 
  Tlength_Blength$Model_summaries$corBrownian$tTable

#the slope between separate sexes and averages is very different; is this because there are fewer species in the averaged dataset?

  ##average the columns, add to mars_sexes; averaging requires un-loggin and re-logging
  mars_sex_Tl_av<-log10((10^(mars_sexes$Bl_M)+10^(mars_sexes$Bl_F))/2)
  mars_sex_Bl_av<-log10((10^(mars_sexes$Tl_M)+10^(mars_sexes$Tl_F))/2)
  mars_sex_av<-cbind(mars_sexes,mars_sex_Tl_av,mars_sex_Bl_av )

  TB_averaged=find.best.model(mars_sex_Tl_av~mars_sex_Bl_av,marsTree_sexes,mars_sex_av);TB_averaged$AIC_Weights

  TB_averaged$Model_summaries$corBrownian
  
# or is the higher slope an artifact of better phylogenetic coverage?
  summary(lm(Tlength_mm~Blength_mm,data=mars))
  summary(lm(Tl_M~Bl_M, data=mars_sex_av))
  summary(lm(Tl_F~Bl_F, data=mars_sex_av))
  summary(lm(mars_sex_Tl_av~mars_sex_Bl_av,data=mars_sex_av))
  summary(lm(mars$Tl_max~mars$Bl_max))
  
#plot male-only, female-only, and averaged datasets together

plot(mars_sexes$Bl_M,mars_sexes$Tl_M, col="red", pch=19);points(mars_sexes$Bl_F,mars_sexes$Tl_F, col="blue", pch=19);points(mars$Blength_mm,mars$Tlength_mm, col="green", pch=19);points(mars$Tl_max~mars$Bl_max, col="pink", pch=19);abline(lm(mars_sexes$Tl_M~mars_sexes$Bl_M), col="red");abline(lm(mars_sexes$Tl_F~mars_sexes$Bl_F), col="blue"); abline(lm(mars$Tlength_mm~mars$Blength_mm), col="green"); abline(lm(mars$Tl_max~mars$Bl_max), col="pink")


#using maximum tail length

  TB_max=find.best.model(Tl_max~Bl_max,marsTree,mars); TB_max$AIC_Weights
  TB_max$Model_summaries$corBrownian
```

#starting on locomotion analysis

```{r}
###but also there must be different scaling patterns according to kangaroo or not

  Roos=find.best.model(Tlength_mm~Blength_mm:Locomotor_mode, marsTree,mars); Roos$AIC_Weights
  
  Roos$Model_summaries$corBrownian

```


#comparing body mass and tail lengths and which one explains tail length better

```{r}

#Body mass and body length- which is better?

#first, determine which phylogenetic correlation structure and tree fit the data best for both models to be compared:
Tlength_Blength=find.best.model(Tlength_mm~Blength_mm,marsTree,mars)
Tlength_Blength$AIC_Weights 
Tlength_Blength$Model_summaries$corBrownian


Tlength_Bwt=find.best.model(Tlength_mm~Wt_g,marsTree,mars)
Tlength_Bwt$AIC_Weights 
Tlength_Bwt$Model_summaries$corBrownian

#now, compare the two:


  


```